CREATE TABLE [dbo].[MasterAgentSource] (
    [rID]                          INT            IDENTITY (1, 1) NOT NULL,
    [AssociateID]                  NVARCHAR (255) NULL,
    [AgentName]                    NVARCHAR (255) NULL,
    [STCode]                       NVARCHAR (255) NULL,
    [AccountType]                  NVARCHAR (255) NULL,
    [Type]                         NVARCHAR (255) NULL,
    [Type2019]                     NVARCHAR (255) NULL,
    [LastSignIn]                   DATETIME       NULL,
    [TerminationDate]              DATETIME       NULL,
    [Participant2020]              NVARCHAR (255) NULL,
    [Participant2019]              NVARCHAR (255) NULL,
    [Participant2018]              NVARCHAR (255) NULL,
    [Participant2017]              NVARCHAR (255) NULL,
    [Participant2016]              NVARCHAR (255) NULL,
    [Participant2015]              NVARCHAR (255) NULL,
    [AgentFirstName]               NVARCHAR (255) NULL,
    [AgentLastName]                NVARCHAR (255) NULL,
    [MarketArea]                   NVARCHAR (255) NULL,
    [MediaState]                   NVARCHAR (255) NULL,
    [MediaCounty]                  NVARCHAR (255) NULL,
    [MediaCity]                    NVARCHAR (255) NULL,
    [MediaZipCode]                 NVARCHAR (255) NULL,
    [DMA]                          NVARCHAR (255) NULL,
    [MSA]                          NVARCHAR (255) NULL,
    [NeilsenAssignment]            NVARCHAR (255) NULL,
    [HomeownersRestricted]         NVARCHAR (255) NULL,
    [AutoRestricted]               NVARCHAR (255) NULL,
    [RentersRestricted]            NVARCHAR (255) NULL,
    [AreaVicePresident]            NVARCHAR (255) NULL,
    [VicePresidentAgency]          NVARCHAR (255) NULL,
    [SalesLeader]                  NVARCHAR (255) NULL,
    [Territory]                    NVARCHAR (255) NULL,
    [AgentOfficeAddr1]             NVARCHAR (255) NULL,
    [AgentOfficeAddr2]             NVARCHAR (255) NULL,
    [AgentOfficeCity]              NVARCHAR (255) NULL,
    [AgentOfficeState]             NVARCHAR (255) NULL,
    [AgentOfficeZipCode]           NVARCHAR (255) NULL,
    [AgentOfficePhone]             NVARCHAR (255) NULL,
    [AgentEmail]                   NVARCHAR (255) NULL,
    [AAS]                          NVARCHAR (255) NULL,
    [RegionalBillingCode]          NVARCHAR (255) NULL,
    [Tier1]                        NVARCHAR (255) NULL,
    [CoopContribution]             NVARCHAR (255) NULL,
    [AppointmentDate]              NVARCHAR (255) NULL,
    [Tenure]                       NVARCHAR (255) NULL,
    [DigitalDeliveryIssue]         NVARCHAR (255) NULL,
    [SpecialPandora]               NVARCHAR (255) NULL,
    [FBRRDeliveryIssue]            NVARCHAR (255) NULL,
    [Languages]                    NVARCHAR (255) NULL,
    [MultiState]                   NVARCHAR (255) NULL,
    [AddlState1]                   NVARCHAR (255) NULL,
    [AddlState2]                   NVARCHAR (255) NULL,
    [AddlState3]                   NVARCHAR (255) NULL,
    [AddlState4]                   NVARCHAR (255) NULL,
    [FacebookLowerAutoRates]       NVARCHAR (255) NULL,
    [RadiusYear]                   NVARCHAR (255) NULL,
    [TargetingRadius]              NVARCHAR (255) NULL,
    [TargetingZipCodes]            NVARCHAR (MAX) NULL,
    [DigitalMediaRadiusPopulation] NVARCHAR (255) NULL,
    [NumberOfTargetedZips]         NVARCHAR (255) NULL,
    [Latitude]                     NVARCHAR (255) NULL,
    [Longitude]                    NVARCHAR (255) NULL,
    [ReusableVoiceRecording]       NVARCHAR (255) NULL,
    [FacebookPage]                 NVARCHAR (255) NULL,
    [CALicense]                    NVARCHAR (255) NULL,
    [CreatedOn]                    DATETIME       NOT NULL,
    [CreatedBy]                    VARCHAR (255)  NOT NULL,
	[Jaytest]					   INT NOT null
    CONSTRAINT [PK_dbo.MasterAgentSources] PRIMARY KEY CLUSTERED ([rID] ASC)
);

