CREATE TABLE [dbo].[MasterBudgetSource] (
    [rID]                     INT             IDENTITY (1, 1) NOT NULL,
    [AssociateID]             NVARCHAR (255)  NULL,
    [AgentFirstName]          NVARCHAR (255)  NULL,
    [AgentLastName]           NVARCHAR (255)  NULL,
    [TerminationDate]         DATETIME        NULL,
    [PaymentDeactivationDate] DATETIME        NULL,
    [PendingReactivationDate] DATETIME        NULL,
    [ReactivationDate]        DATETIME        NULL,
    [Closed]                  DATETIME        NULL,
    [ActivateOn]              DATETIME        NULL,
    [EnrollmentPeriod]        NVARCHAR (255)  NULL,
    [AgentType]               NVARCHAR (255)  NULL,
    [RegionalBillingCode]     NVARCHAR (255)  NULL,
    [Vendor]                  NVARCHAR (255)  NULL,
    [Tactic]                  NVARCHAR (255)  NULL,
    [CampaignType]            NVARCHAR (255)  NULL,
    [AssociateIDTactic]       NVARCHAR (255)  NULL,
    [PackageID]               NVARCHAR (255)  NULL,
    [SocialPlacement]         NVARCHAR (255)  NULL,
    [SelectedProduct]         NVARCHAR (255)  NULL,
    [TargetDemo]              NVARCHAR (255)  NULL,
    [OrderBaseTactic]         NVARCHAR (255)  NULL,
    [OriginalBudget]          DECIMAL (18, 2) NULL,
    [FinalBudget]             DECIMAL (18, 2) NULL,
    [AdServingBudget]         DECIMAL (18, 2) NULL,
    [BrandSafetyCostDV]       DECIMAL (18, 2) NULL,
    [BrandSafetyCostIAS]      DECIMAL (18, 2) NULL,
    [SBMSBudget]              DECIMAL (18, 2) NULL,
    [DMA]                     NVARCHAR (255)  NULL,
    [EstimateNumber]          INT             NOT NULL,
    [UrlType]                 NVARCHAR (255)  NULL,
    [RentersUrlType]          NVARCHAR (255)  NULL,
    [StartMonth]              NVARCHAR (255)  NULL,
    [EndMonth]                NVARCHAR (255)  NULL,
    [radius]                  INT             NULL,
    [CreatedOn]               DATETIME        NOT NULL,
    [CreatedBy]               VARCHAR (255)   NOT NULL,
    CONSTRAINT [PK_dbo.ArrowBudget] PRIMARY KEY CLUSTERED ([rID] ASC)
);

