CREATE TABLE [dbo].[PacingMonthly] (
    [RecordID]                    INT             IDENTITY (1, 1) NOT NULL,
    [ProcessSource]               VARCHAR (255)   NOT NULL,
    [ClientID]                    INT             NOT NULL,
    [EnrollmentPeriod]            INT             NULL,
    [DataRunPeriod]               DATE            NOT NULL,
    [DataRunCount]                INT             NOT NULL,
    [MonthNum]                    INT             NOT NULL,
    [Year]                        INT             NOT NULL,
    [ReportingTactic]             VARCHAR (255)   NULL,
    [Vendor]                      VARCHAR (255)   NULL,
    [AssociateID]                 VARCHAR (255)   NULL,
    [AgentName]                   VARCHAR (255)   NULL,
    [TerminationDate]             DATETIME        NULL,
    [Segment]                     VARCHAR (255)   NULL,
    [MarketArea]                  VARCHAR (255)   NULL,
    [MediaState]                  VARCHAR (255)   NULL,
    [STCode]                      VARCHAR (255)   NULL,
    [Type2019]                    VARCHAR (255)   NULL,
    [Radius]                      INT             NULL,
    [NumberOfTargetedZips]        VARCHAR (255)   NULL,
    [ImpressionsPlanned]          DECIMAL (18, 2) NULL,
    [ImpressionsDelivered]        DECIMAL (18, 2) NULL,
    [ImpressionsPacingRange]      VARCHAR (100)   NULL,
    [ImpressionsPercentDelivered] VARCHAR (100)   NULL,
    [ZeroDollarImpressionsFlag]   VARCHAR (100)   NULL,
    [Clicks]                      DECIMAL (18, 2) NULL,
    [ClicksPlanned]               DECIMAL (18, 2) NULL,
    [ClicksPercent]               VARCHAR (100)   NULL,
    [ClicksPacingRange]           VARCHAR (100)   NULL,
    [SBMSBudget]                  DECIMAL (18, 2) NULL,
    [PeriodSpend]                 DECIMAL (18, 4) NULL,
    [PercentOfBudget]             DECIMAL (18, 2) NULL,
    [TotalPlannedMonths]          INT             NULL,
    [OutOfScheduleFlag]           VARCHAR (100)   NULL,
    [PaymentDeactivationDate]     DATETIME        NULL,
    [TargetDemo]                  VARCHAR (255)   NULL,
    [CTR]                         DECIMAL (18, 2) NULL,
    [CPM]                         DECIMAL (18, 2) NULL,
    [Flag]                        VARCHAR (100)   NULL,
    [Note]                        VARCHAR (255)   NULL,
    [NoteCreatedOn]               DATETIME2 (0)   NULL,
    [CreatedOn]                   DATETIME2 (0)   NOT NULL,
    [CreatedBy]                   VARCHAR (100)   NOT NULL,
    [UpdatedOn]                   DATETIME        NULL,
    [UpdatedBy]                   VARCHAR (100)   NULL,
    [Severity]                    VARCHAR (100)   NULL
);

