CREATE TABLE [dbo].[PacingTotal] (
    [RecordId]                INT             IDENTITY (1, 1) NOT NULL,
    [ReportingTactic]         NVARCHAR (255)  NULL,
    [Vendor]                  NVARCHAR (255)  NULL,
    [Segment]                 NVARCHAR (255)  NULL,
    [MarketArea]              NVARCHAR (255)  NULL,
    [MediaState]              NVARCHAR (255)  NULL,
    [AssociateID]             NVARCHAR (255)  NULL,
    [STCode]                  NVARCHAR (255)  NULL,
    [Type2019]                NVARCHAR (255)  NULL,
    [AGENTNAME]               NVARCHAR (255)  NULL,
    [TerminationDate]         DATETIME        NULL,
    [Radius]                  INT             NULL,
    [NumberOfTargetedZips]    INT             NULL,
    [TotalPlannedImpressions] DECIMAL (18, 2) NULL,
    [PlannedMonths]           INT             NULL,
    [ImpressionsPerMonth]     DECIMAL (18, 2) NULL,
    [SBMSBudget]              DECIMAL (18, 2) NULL,
    [ImpressionsToDate]       DECIMAL (18, 2) NULL,
    [ClicksToDate]            DECIMAL (18, 2) NULL,
    [SpendToDate]             DECIMAL (18, 4) NULL,
    [CompletedMonths]         INT             NULL,
    [PaymentDeactivationDate] DATETIME        NULL,
    [TargetDemo]              NVARCHAR (255)  NULL,
    [CreatedOn]               DATETIME        NULL,
    [CreatedBy]               NVARCHAR (255)  NULL,
    [ProcessSource]           NVARCHAR (255)  NULL,
    [Note]                    VARCHAR (255)   NULL,
    [NoteCreatedOn]           DATETIME2 (0)   NULL,
    [NoteCreatedby]           VARCHAR (255)   NULL,
    PRIMARY KEY CLUSTERED ([RecordId] ASC)
);

